CUDNN:
  BENCHMARK: true
  DETERMINISTIC: false
  ENABLED: true
GPUS: (0,)
OUTPUT_DIR: "output"
LOG_DIR: "log"
WORKERS: 4
PRINT_FREQ: 50
LOG_CONFIG: logging.conf
SEED: 2019

DATASET:
  NUM_CLASSES: 6
  ROOT: "/home/username/data/dutch/data"
  CLASS_WEIGHTS: [0.7151, 0.8811, 0.5156, 0.9346, 0.9683, 0.9852]

MODEL:
  NAME: patch_deconvnet_skip
  IN_CHANNELS: 1


TRAIN:
  BATCH_SIZE_PER_GPU: 64
  BEGIN_EPOCH: 0
  END_EPOCH: 100
  MIN_LR: 0.001
  MAX_LR: 0.02
  MOMENTUM: 0.9
  WEIGHT_DECAY: 0.0001
  SNAPSHOTS: 5
  AUGMENTATION: True
  DEPTH: "none" # Options are No, Patch and Section
  STRIDE: 50
  PATCH_SIZE: 99
  AUGMENTATIONS:
    RESIZE:
      HEIGHT: 99
      WIDTH: 99
    PAD:
      HEIGHT: 99
      WIDTH: 99
  MEAN: 0.0009997 
  STD: 0.20977
  MODEL_DIR: "models"

VALIDATION:
  BATCH_SIZE_PER_GPU: 512

TEST: 
  # Uncomment this if you want to test a model:
  # MODEL_PATH: "/your/trained/model/path/model_name.pth" # must be an absolute path
  TEST_STRIDE: 10
  SPLIT: "test1" # Can be both, test1, test2
  INLINE: True
  CROSSLINE: True
  POST_PROCESSING: 
    SIZE: 99 # 
    CROP_PIXELS: 0 # Number of pixels to crop top, bottom, left and right

